const emotionObj = {
  "emotion_baiyan": "[白眼]",
  "emotion_baobao": "[拥抱]",
  "emotion_baoquan":"[抱拳]",
  "emotion_bianbian":"[便便]",
  "emotion_biezui":"[撇嘴]",
  "emotion_bishi":"[鄙视]",
  "emotion_bizui":"[闭嘴]",
  "emotion_cahan":"[擦汗]",
  "emotion_ciya":"[呲牙]",
  "emotion_dabing":"[大兵]",
  "emotion_daku":"[大哭]",
  "emotion_deyi":"[得意]",
  "emotion_guzhang":"[鼓掌]",
  "emotion_haixiu":"[害羞]",
  "emotion_hanxiao":"[憨笑]",
  "emotion_haqian":"[哈欠]",
  "emotion_huaixiao":"[坏笑]",
  "emotion_jie":"[饥饿]",
  "emotion_keai":"[可爱]",
  "emotion_kelian":"[可怜]",
  "emotion_koubi":"[抠鼻]",
  "emotion_ku":"[酷]",
  "emotion_kuaikule":"[快哭了]",
  "emotion_kun":"[困]",
  "emotion_lenghan":"[冷汗]",
  "emotion_liuhan":"[流汗]",
  "emotion_shui":"[睡]",
  "emotion_touxiao":"[偷笑]",
  "emotion_tu":"[吐]",
  "emotion_weiqu":"[委屈]",

}

export default emotionObj