export const storageItem = 'weStorage-'
export const phone = 'phone'
export const openId = 'openId'
export const userId = 'userId'
export const token = 'token'
export const shopId = 'shopId'
export const shopName = 'shopName'
